class AddColumnsToTemporarylists < ActiveRecord::Migration[5.1]
  def change
    add_column :temporary_lists, :gender, :string
    add_column :temporary_lists, :country, :string
    add_column :temporary_lists, :arts, :string
    add_column :temporary_lists, :cooking, :string
    add_column :temporary_lists, :hiking, :string
    add_column :temporary_lists, :networking, :string
    add_column :temporary_lists, :video_games, :string
    add_column :temporary_lists, :book, :string
    add_column :temporary_lists, :dining_out, :string
    add_column :temporary_lists, :movies, :string
    add_column :temporary_lists, :nightclubs, :string
    add_column :temporary_lists, :religion, :string
    add_column :temporary_lists, :charity, :string
    add_column :temporary_lists, :museum, :string
    add_column :temporary_lists, :shopping, :string
    add_column :temporary_lists, :wine, :string
    add_column :temporary_lists, :coffee, :string
    add_column :temporary_lists, :gardening, :string
    add_column :temporary_lists, :pets, :string
    add_column :temporary_lists, :aerobics, :string
    add_column :temporary_lists, :golf, :string
    add_column :temporary_lists, :martial_arts, :string
    add_column :temporary_lists, :soccer, :string
    add_column :temporary_lists, :walking, :string
    add_column :temporary_lists, :rugby, :string
    add_column :temporary_lists, :swimming, :string
    add_column :temporary_lists, :baseball, :string
    add_column :temporary_lists, :cycling, :string
    add_column :temporary_lists, :running, :string
    add_column :temporary_lists, :tennis, :string
    add_column :temporary_lists, :weight, :string
    add_column :temporary_lists, :basketball, :string
    add_column :temporary_lists, :skiing, :string
    add_column :temporary_lists, :volleyball, :string
    add_column :temporary_lists, :being_blinded, :string
    add_column :temporary_lists, :willing_experiment, :string
    add_column :temporary_lists, :costume, :string
    add_column :temporary_lists, :role_playing, :string
    add_column :temporary_lists, :using_sex_toys, :string
    add_column :temporary_lists, :unusual_places, :string
    add_column :temporary_lists, :being_watched, :string
    add_column :temporary_lists, :independent, :string
    add_column :temporary_lists, :mature, :string
    add_column :temporary_lists, :outgoing, :string
    add_column :temporary_lists, :self_confident, :string
    add_column :temporary_lists, :cultivated, :string
    add_column :temporary_lists, :reliable, :string
    add_column :temporary_lists, :spiritual, :string
    add_column :temporary_lists, :imaginative, :string
    add_column :temporary_lists, :sophisticated, :string
    add_column :temporary_lists, :username, :string
    add_column :temporary_lists, :city, :string
    add_column :temporary_lists, :description, :text
    add_column :temporary_lists, :age, :integer
    add_column :temporary_lists, :marital_status, :string
    add_column :temporary_lists, :anything_exciting, :string
    add_column :temporary_lists, :long_term, :string
    add_column :temporary_lists, :open_anything, :string
    add_column :temporary_lists, :short_term, :string
    add_column :temporary_lists, :undecided, :string
    add_column :temporary_lists, :virtual, :string
    add_column :temporary_lists, :height, :integer
    add_column :temporary_lists, :hair_color, :string
    add_column :temporary_lists, :eye_color, :string
    add_column :temporary_lists, :smoker, :string
    add_column :temporary_lists, :anything_goes, :string
    add_column :temporary_lists, :dominated, :string
    add_column :temporary_lists, :dominate, :string
    add_column :temporary_lists, :normal, :string
    add_column :temporary_lists, :threesome, :string
    add_column :temporary_lists, :secret, :string
    add_column :temporary_lists, :active, :string
    add_column :temporary_lists, :shy, :string
    add_column :temporary_lists, :sociable, :string
    add_column :temporary_lists, :fun, :string
    add_column :temporary_lists, :generous, :string
    add_column :temporary_lists, :relaxed, :string
    add_column :temporary_lists, :moody, :string
    add_column :temporary_lists, :modest, :string
    add_column :temporary_lists, :sensitive, :string
    add_column :temporary_lists, :photos, :text, array: true, default: []
  end
end
